<script setup>
import { Form, Field } from 'vee-validate';
import * as Yup from 'yup';

import { useBoatsStore, useAlertStore } from '@/stores';
import { router } from '@/router';

const schema = Yup.object().shape({
    firstName: Yup.string()
        .required('First Name is required'),
    lastName: Yup.string()
        .required('Last Name is required'),
    username: Yup.string()
        .required('Username is required'),
    password: Yup.string()
        .required('Password is required')
        .min(6, 'Password must be at least 6 characters')
});

const boatSchema = Yup.object().shape({
  //id: Yup.number()
  //  .positive('Id must be positive')
 //   .integer('Id must be an integer')
 //   .notRequired(), // Usually generated by DB, so not required on input

  name: Yup.string()
    .required('Name is required'),

  description: Yup.string()
    .notRequired(),

  capacity: Yup.number()
    .positive('Capacity must be positive')
    .integer('Capacity must be an integer')
    .notRequired(),

  size: Yup.number()
    .integer('Size must be an integer')
    .notRequired(),

  type: Yup.string()
    .oneOf(['TYPE1', 'TYPE2', 'TYPE3'], 'Invalid boat type') // replace with your actual BoatType enum values
    .required('Type is required'),

  createdAt: Yup.date()
    .notRequired(), // managed by backend

  updatedAt: Yup.date()
    .notRequired()  // managed by backend
});

async function onSubmit(values) {
    const boatsStore = useBoatsStore();
    const alertStore = useAlertStore();
    try {
        await boatsStore.register(values);
        await router.push('/account/login');
        alertStore.success('Registration successful');
    } catch (error) { 
        alertStore.error(error);
    }
}
</script>

<template>
  <div class="card m-3">
    <h4 class="card-header">Boat Registration2</h4>
    <div class="card-body">
      <Form @submit="onSubmit" :validation-schema="boatSchema" v-slot="{ errors, isSubmitting }">
        
        <div class="form-group">
          <label>Name</label>
          <Field
            name="name"
            type="text"
            class="form-control"
            :class="{ 'is-invalid': errors.name }"
          />
          <div class="invalid-feedback">{{ errors.name }}</div>
        </div>

        <div class="form-group">
          <label>Description</label>
          <Field
            name="description"
            type="text"
            class="form-control"
            :class="{ 'is-invalid': errors.description }"
          />
          <div class="invalid-feedback">{{ errors.description }}</div>
        </div>

        <div class="form-group">
          <label>Capacity</label>
          <Field
            name="capacity"
            type="number"
            class="form-control"
            :class="{ 'is-invalid': errors.capacity }"
          />
          <div class="invalid-feedback">{{ errors.capacity }}</div>
        </div>

        <div class="form-group">
          <label>Size</label>
          <Field
            name="size"
            type="number"
            class="form-control"
            :class="{ 'is-invalid': errors.size }"
          />
          <div class="invalid-feedback">{{ errors.size }}</div>
        </div>

        <div class="form-group">
          <label>Type</label>
          <Field
            name="type"
            as="select"
            class="form-control"
            :class="{ 'is-invalid': errors.type }"
          >
            <option value="" disabled>Select a type</option>
            <option value="TYPE1">TYPE1</option>
            <option value="TYPE2">TYPE2</option>
            <option value="TYPE3">TYPE3</option>
            <!-- Replace with your actual BoatType enum options -->
          </Field>
          <div class="invalid-feedback">{{ errors.type }}</div>
        </div>

        <div class="form-group">
          <button class="btn btn-primary" :disabled="isSubmitting">
            <span v-show="isSubmitting" class="spinner-border spinner-border-sm mr-1"></span>
            Submit
          </button>
          <router-link to="/" class="btn btn-link">Cancel</router-link>
        </div>
      </Form>
    </div>
  </div>
</template>

